// Generic production cloth material template.
// The GUI replaces all character texture tokens per PMX material.
#define EF_CLOTH_MAIN_TEXTURE_RESOURCE \
    "__EF_CLOTH_BASE_TEXTURE__"
#define EF_CLOTH_NORMAL_TEXTURE_RESOURCE \
    "__EF_CLOTH_NORMAL_TEXTURE__"
#define EF_CLOTH_PROPERTY_TEXTURE_RESOURCE \
    "__EF_CLOTH_PROPERTY_TEXTURE__"
#define EF_CLOTH_RD_TEXTURE_RESOURCE \
    "__EF_CLOTH_RD_TEXTURE__"
#define EF_CLOTH_LUT_TEXTURE_RESOURCE \
    "__EF_CLOTH_LUT_TEXTURE__"
#define EF_CLOTH_RS_TEXTURE_RESOURCE \
    "__EF_CLOTH_RS_TEXTURE__"
#define EF_CLOTH_ENV_TEXTURE_RESOURCE \
    "textures/common/cloth_environment_current.dds"
#define EF_CLOTH_MATCAP_ENABLED 1
#define EF_CLOTH_MATCAP_TEXTURE_RESOURCE \
    "textures/common/Eff_MatCap_019.png"
#define EF_CLOTH_MATCAP_MANUAL_LOD_ENABLED 1
#define EF_CLOTH_MATCAP_MANUAL_TEXTURE_RESOURCE \
    "textures/common/Eff_MatCap_019_manual_lod.png"
#define EF_CLOTH_MATCAP_SOURCE_SIZE 256.0
#define EF_CLOTH_MATCAP_MANUAL_LOD_COUNT 8.0
#define EF_CLOTH_MATCAP_LOD_SCALE 1.0
#define EF_CLOTH_MATCAP_LOD_BIAS 0.0
#define EF_CLOTH_MATCAP_LOD_OVERRIDE -1.0
#define EF_CLOTH_FGD_LUT_ENABLED 1
#define EF_CLOTH_FGD_TEXTURE_RESOURCE \
    "textures/common/PreIntegratedFGD_GGXDisneyDiffuse.png"
#define EF_CLOTH_FGD_STRENGTH 1.00
#define EF_CLOTH_CULL_MODE NONE
#define EF_CLOTH_OUTLINE_ENABLED 0
#define EF_OUTLINE_CONTROLLER_ENABLED 0
#define EF_CLOTH_LIGHT_CURVE 1.0
#define EF_CLOTH_RD_COLOR_STRENGTH 0.35
#define EF_CLOTH_LUT_STRENGTH 0.0
#define EF_CLOTH_LUT_USE_BRG 1
#define EF_CLOTH_DARK_STRENGTH 0.56
#define EF_CLOTH_LIGHT_STRENGTH 1.12
#define EF_CLOTH_NORMAL_STRENGTH 1.0
#define EF_CLOTH_LAYERED_DIELECTRIC_ENABLED 1
#define EF_CLOTH_LAYER_COAT_STRENGTH 0.40
#define EF_CLOTH_LAYER_COAT_FLOOR 0.02
#define EF_CLOTH_LAYER_SMOOTH_START 0.30
#define EF_CLOTH_LAYER_SMOOTH_END 0.72
#define EF_CLOTH_AO_DARK_STRENGTH 0.65
#define EF_CLOTH_AO_LIGHT_STRENGTH 0.25
#define EF_CLOTH_AO_DEBUG 0
#define EF_CLOTH_METALLIC_STRENGTH 1.0
#define EF_CLOTH_ROUGHNESS_STRENGTH 1.0
#define EF_CLOTH_RAIN_ENABLED 1
// This is the controller's upper endpoint. The RainAmount morph defaults to 0.
#define EF_CLOTH_RAIN_AMOUNT 1.5
#define EF_CLOTH_WET_TARGET_ROUGHNESS 0.12
#define EF_CLOTH_RAIN_TEXTURE_RESOURCE \
    "textures/common/rain/T_actor_common_rain_02_M.png"
#define EF_CLOTH_RAIN_UV_SCALE 2.3
#define EF_CLOTH_RAIN_NORMAL_STRENGTH 1.25
#define EF_CLOTH_RAIN_SECONDARY_ENABLED 1
#define EF_CLOTH_RAIN_SECONDARY_SCALE_OFFSET 5.0
#define EF_CLOTH_RAIN_SECONDARY_STRENGTH 0.55
#define EF_CLOTH_RAIN_FLOW_SPEED 0.08
#define EF_CLOTH_RAIN_DROP_ENABLED 1
#define EF_CLOTH_RAIN_DROP_TEXTURE_RESOURCE \
    "textures/common/rain/rain_drops.png"
#define EF_CLOTH_RAIN_DROP_PHASE_TEXTURE_RESOURCE \
    "textures/common/rain/rain_drops_phase.png"
#define EF_CLOTH_RAIN_DROP_TILING 3.5
#define EF_CLOTH_RAIN_DROP_INTENSITY 1.0
#define EF_CLOTH_RAIN_DROP_SPEED 0.25
#define EF_CLOTH_RAIN_DROP_LIFETIME 0.65
#define EF_CLOTH_RAIN_DROP_NORMAL_OFFSET 0.72
#define EF_CLOTH_RAIN_DROP_EDGE_SMOOTHNESS 2.3
#define EF_CLOTH_RAIN_DROP_OMNI_COVERAGE 0.0
#define EF_CLOTH_RAIN_DROP_NORMAL_STRENGTH 1.0
#define EF_CLOTH_RAIN_COAT_ENABLED 1
#define EF_CLOTH_RAIN_COAT_STRENGTH 0.65
#define EF_CLOTH_RAIN_COAT_ENV_STRENGTH 0.35
#define EF_CLOTH_RAIN_COAT_ROUGHNESS 0.10
#define EF_CLOTH_RAIN_COAT_F0 0.02
#define EF_CLOTH_RAIN_CHANNEL_DEBUG 0
#define EF_CLOTH_RAIN_NORMAL_X_SIGN 1.0
#define EF_CLOTH_RAIN_NORMAL_Y_SIGN 1.0
#define EF_CLOTH_REFLECTIVITY_STRENGTH 1.0
#define EF_CLOTH_DIELECTRIC_F0 0.08
#define EF_CLOTH_RS_STRENGTH 1.0
#define EF_CLOTH_SPECULAR_STRENGTH 2.0
#define EF_CLOTH_SPECULAR_MAX 20.0
#define EF_CLOTH_SPECULAR_VIEW_LOCK 0.65
#define EF_CLOTH_SPECULAR_LIGHT_FLOOR 0.05
#define EF_CLOTH_DIRECT_METAL_TINT_STRENGTH 0.08
#ifndef EF_CLOTH_BROAD_SPECULAR_STRENGTH
#define EF_CLOTH_BROAD_SPECULAR_STRENGTH 1.35
#endif
#ifndef EF_CLOTH_BROAD_SPECULAR_ROUGHNESS
#define EF_CLOTH_BROAD_SPECULAR_ROUGHNESS 0.58
#endif
#ifndef EF_CLOTH_BROAD_SPECULAR_NORMAL_SMOOTHING
#define EF_CLOTH_BROAD_SPECULAR_NORMAL_SMOOTHING 0.40
#endif
#define EF_CLOTH_BROAD_SPECULAR_TINT_STRENGTH 0.08
#define EF_CLOTH_BROAD_SPECULAR_METALLIC_REJECTION 2.0
#ifndef EF_CLOTH_ANISO_SPECULAR_STRENGTH
#define EF_CLOTH_ANISO_SPECULAR_STRENGTH 0.60
#endif
#define EF_CLOTH_ANISO_AMOUNT 0.55
#define EF_CLOTH_ANISO_AXIS 1.0
#define EF_CLOTH_ANISO_ROUGHNESS_FLOOR 0.28
#define EF_CLOTH_ANISO_NORMAL_SMOOTHING 0.65
#define EF_CLOTH_ANISO_TINT_STRENGTH 0.08
#define EF_CLOTH_ANISO_METALLIC_REJECTION 2.0
#define EF_CLOTH_ANISO_FACING_START 0.15
#define EF_CLOTH_ANISO_FACING_END 0.45
#define EF_CLOTH_ANISO_THRESHOLD_DEBUG 0
#define EF_CLOTH_ANISO_DEBUG_THRESHOLD 0.003
#define EF_CLOTH_RIM_STRENGTH 0.55
#define EF_CLOTH_RIM_WIDTH 0.30
#define EF_CLOTH_RIM_SOFTNESS 0.08
#define EF_CLOTH_RIM_LIGHT_START 0.05
#define EF_CLOTH_RIM_LIGHT_END 0.45
#define EF_CLOTH_RIM_NORMAL_SMOOTHING 0.90
#define EF_CLOTH_RIM_ALBEDO_BLEND 0.20
#define EF_CLOTH_RIM_METAL_RETENTION 0.55
#define EF_CLOTH_SCREEN_RIM_ENABLED 1
#define EF_CLOTH_SHADOW_VIEWPORT_MAP ZMDshadow_ViewportMap2
#define EF_CLOTH_SHADOW_CONTROLLER_NAME "ZMDshadow.x"
#define EF_CLOTH_SCREEN_RIM_WIDTH_X 0.041847
#define EF_CLOTH_SCREEN_RIM_WIDTH_Y 0.019108
#define EF_CLOTH_SCREEN_RIM_VIEW_SCALE 0.1
#define EF_CLOTH_SCREEN_RIM_MODEL_SCALE 10.0
#define EF_CLOTH_SCREEN_RIM_DEPTH_SCALE 0.8
#define EF_CLOTH_SCREEN_RIM_DEPTH_MAX 4.0
#define EF_CLOTH_SCREEN_RIM_FRESNEL_POWER 3.0
#define EF_CLOTH_SCREEN_RIM_LIGHT_START 0.0
#define EF_CLOTH_SCREEN_RIM_LIGHT_END 0.2
#define EF_CLOTH_SCREEN_RIM_STRENGTH 0.45
#define EF_CLOTH_SCREEN_RIM_COLOR float3(1.0, 1.0, 1.0)
#define EF_CLOTH_SCREEN_RIM_METAL_RETENTION 0.55
#define EF_CLOTH_ZMD_SHADOW_ENABLED 1
#define EF_CLOTH_SHADOW_CENTER 0.5
#define EF_CLOTH_SHADOW_SMOOTHNESS 0.35
#define EF_CLOTH_SHADOW_OFFSET 0.0
#define EF_CLOTH_SHADOW_STRENGTH 1.0
#define EF_CLOTH_DIRECT_SHADOW_FLOOR 0.02
#define EF_CLOTH_ENV_SHADOW_STRENGTH 0.75
#define EF_CLOTH_RIM_SHADOW_STRENGTH 0.75
#define EF_CLOTH_SHADOW_DEBUG 0
#define EF_CLOTH_CONTROLLER_ENABLED 1
#define EF_CLOTH_CONTROLLER_NAME "EndfieldCloth_controller.pmx"
#define EF_CLOTH_CONTROLLER_MAX_MULTIPLIER 5.0
#define EF_CLOTH_ENV_STRENGTH 0.80
#define EF_CLOTH_HDR_RELATIVE_STRENGTH 0.65
#define EF_CLOTH_ENV_ROTATION 0.0
#define EF_CLOTH_ENV_MIP_COUNT 7.0
#define EF_CLOTH_ENV_RGBM_RANGE 6.0
#define EF_CLOTH_ENV_DESATURATION 1.0
#define EF_CLOTH_ENV_METAL_TINT_STRENGTH 0.05
#define EF_CLOTH_ENV_AO_STRENGTH 0.65
#define EF_CLOTH_ENV_COLOR float3(1.0, 1.0, 1.0)

#include "internal/endfield_cloth.hlsl"
