// Generic production skin template with MMD native edge geometry.
// The GUI replaces all character texture tokens per PMX material.
#define EF_SKIN_MAIN_TEXTURE_RESOURCE \
    "__EF_SKIN_BASE_TEXTURE__"
#define EF_SKIN_RD_TEXTURE_RESOURCE \
    "__EF_SKIN_RD_TEXTURE__"
#define EF_SKIN_LUT_TEXTURE_RESOURCE \
    "__EF_SKIN_LUT_TEXTURE__"
#define EF_SKIN_CULL_MODE NONE
#define EF_SKIN_LIGHT_CURVE 1.0
#define EF_SKIN_RD_COLOR_STRENGTH 0.35
#define EF_SKIN_RD_DARK_STRENGTH 0.82
#define EF_SKIN_RD_LIGHT_STRENGTH 1.12
#define EF_SKIN_LUT_STRENGTH 0.35
#define EF_SKIN_LUT_USE_BRG 1
#define EF_SKIN_SSS_ENABLED 1
#define EF_SKIN_SSS_RANGE 0.5
#define EF_SKIN_SSS_STRENGTH 1.0
#define EF_SKIN_SSS_COLOR float3(0.822936177, 0.669170380, 0.648408771)
#define EF_SKIN_SPECULAR_ENABLED 1
#define EF_SKIN_SPECULAR_STRENGTH 0.65
#define EF_SKIN_SPECULAR_ROUGHNESS 0.58
#define EF_SKIN_SPECULAR_REFLECTIVITY 0.50
#define EF_SKIN_SPECULAR_COLOR float3(1.0, 0.94, 0.92)
#define EF_SKIN_SPECULAR_LIGHT_END 0.30
#define EF_SKIN_ZMD_SHADOW_ENABLED 1
#define EF_SKIN_SHADOW_CENTER 0.5
#define EF_SKIN_SHADOW_SMOOTHNESS 0.35
#define EF_SKIN_SHADOW_OFFSET 0.0
#define EF_SKIN_SHADOW_STRENGTH 1.0
#define EF_SKIN_RIM_ENABLED 1
#define EF_SKIN_RIM_AREA 0.35
#define EF_SKIN_RIM_STRENGTH 1.17
#define EF_SKIN_RIM_COLOR float3(1.0, 0.82, 0.78)
#define EF_SKIN_RIM_DIFFUSE_EFFECT 0.5
#define EF_SKIN_SCREEN_RIM_ENABLED 1
#define EF_SKIN_SCREEN_RIM_WIDTH_X 0.041847
#define EF_SKIN_SCREEN_RIM_WIDTH_Y 0.019108
#define EF_SKIN_SCREEN_RIM_VIEW_SCALE 0.1
#define EF_SKIN_SCREEN_RIM_MODEL_SCALE 10.0
#define EF_SKIN_SCREEN_RIM_DEPTH_SCALE 0.8
#define EF_SKIN_SCREEN_RIM_DEPTH_MAX 4.0
#define EF_SKIN_SCREEN_RIM_FRESNEL_POWER 3.0
#define EF_SKIN_SCREEN_RIM_LIGHT_START 0.0
#define EF_SKIN_SCREEN_RIM_LIGHT_END 0.2
#define EF_SKIN_SCREEN_RIM_STRENGTH 0.7
#define EF_SKIN_SCREEN_RIM_COLOR float3(1.0, 0.82, 0.78)
#define EF_SKIN_CONTROLLER_ENABLED 1
#define EF_SKIN_CONTROLLER_NAME "EndfieldSkin_controller.pmx"
#define EF_SKIN_CONTROLLER_MAX_MULTIPLIER 5.0
#define EF_SKIN_SPECULAR_CONTROLLER_MAX_MULTIPLIER 25.0
#define EF_SKIN_OUTLINE_ENABLED 0
#define EF_OUTLINE_CONTROLLER_ENABLED 0

#include "internal/endfield_skin.hlsl"
