// Endfield hair release template used by generated character FX files.
// Diffuse/highlight stay in one linear main pass; the screen-space depth rim
// uses a separate additive pass to remain within DirectX 9 ps_3_0 limits.
#define EF_HAIR_RD_GOO_RIM_COMPOSITE_DEBUG 0
#define EF_HAIR_FINAL_RIM_PASS 1
#define EF_HAIR_RD_KK_RS_COMPOSITE_DEBUG 1
#define EF_HAIR_RD_TOP_LIGHT_DEBUG 1
#define EF_HAIR_RD_DARK_LINE_DEBUG 1
#define EF_HAIR_NORMALIZE_MMD_LIGHT_INTENSITY 1
#define EF_HAIR_TOP_LIGHT_CONE_DEBUG 1
#define EF_HAIR_KK_SHAPE_SCALE_DEBUG 1
#define EF_HAIR_KK_JAGGED_CONTROL_DEBUG 1
#define EF_HAIR_KK_SHARP_BAND_DEBUG 1
#define EF_HAIR_KK_ARTICLE_RANGE_FRONT_DEBUG 1
#define EF_HAIR_KK_GOO_LENGTH_FRONT_DEBUG 0
#define EF_HAIR_KK_FRONT_NOV_WIDEN_DEBUG 1
#define EF_HAIR_KK_FRONT_NOV_POWER 0.275
#define EF_HAIR_KK_FRONT_BAND_HARDEN_DEBUG 0
#define EF_HAIR_KK_GOO_AB_COLOR_DEBUG 1
#define EF_HAIR_KK_GOO_RS_FUSION 1
#define EF_HAIR_GOO_RS_FUSION_STRENGTH 0.35
#define EF_HAIR_GOO_RS_DIELECTRIC_GAIN 0.28
#define EF_HAIR_GOO_UPPER_COLOR_MIX 0.35
#define EF_HAIR_KK_FRONT_EDGE_TUNE_DEBUG 1
#define EF_HAIR_KK_FRONT_UPPER_CUT_SOFTNESS 0.015
#define EF_HAIR_KK_FRONT_LOWER_FADE_POWER 0.75
#define EF_HAIR_KK_FRONT_LOWER_ONE_SIDED 1
#define EF_HAIR_HIGHLIGHT_INTENSITY 1.05

#define EF_HAIR_CONTROLLER_ENABLED 1
#define EF_HAIR_CONTROLLER_C5_ENABLED 1
#define EF_HAIR_CONTROLLER_RANGE5_ENABLED 1
#define EF_HAIR_CONTROLLER_MAX_MULTIPLIER 5.0
#define EF_HAIR_CONTROLLER_OFFSET_SCALE 5.0
#define EF_HAIR_CONTROLLER_BASE_GRADE_ENABLED 1
#define EF_HAIR_CONTROLLER_BASE_GRADE_VERTEX_PRECOMPUTE 1
#define EF_HAIR_CONTROLLER_C5_HNORMAL_ENABLED 1
#define EF_HAIR_CONTROLLER_C5_SHAPE_ENABLED 1
#define EF_HAIR_CONTROLLER_C5_DIFFUSE_ENABLED 1
#define EF_HAIR_CONTROLLER_NAME "EndfieldHair_controller_Range5.pmx"

#define EF_HAIR_KK_BAND_EDGE_LOW 0.35
#define EF_HAIR_KK_BAND_EDGE_HIGH 0.55
#define EF_SHADOW_VIEWPORT_MAP ZMDshadow_ViewportMap2
#define EF_SHADOW_CONTROLLER_NAME "ZMDshadow.x"
#define EF_HAIR_P_MATCH_BLEND_SRGB 1

#define EF_MAIN_TEXTURE_RESOURCE "__EF_HAIR_BASE_TEXTURE__"
#define EF_NORMAL_TEXTURE "__EF_HAIR_NORMAL_TEXTURE__"
#define EF_ORM_TEXTURE "__EF_HAIR_PROPERTY_TEXTURE__"
#define EF_RAMP_TEXTURE "__EF_HAIR_RD_TEXTURE__"
#define EF_HAIR_ANISO_NOISE_TEXTURE "__EF_HAIR_ST_TEXTURE__"
#define EF_HAIR_LINE_TEXTURE "__EF_HAIR_LINE_TEXTURE__"
#define EF_HAIR_SPEC_TEXTURE "__EF_HAIR_RS_TEXTURE__"

#define EF_BASE_COLOR float3(0.98588085, 0.98588085, 0.98588085)
#define EF_BASE_COLOR_POW 1.0
#define EF_BUMP_SCALE 1.0
#define EF_AO_STRENGTH 1.0
#define EF_RD_HALFLAMBERT_CENTER 0.57000005245
#define EF_RD_HALFLAMBERT_SHARP 0.18000000715
#define EF_RD_GLOBAL_SHADOW_MIN -1.7261145115
#define EF_RD_GLOBAL_SHADOW_MAX 1.0
#define EF_RD_DIRECT_SHADOW_FLOOR 0.23467295
#define EF_ALBEDO_DARK_STRENGTH 0.8
#define EF_ALBEDO_DARK_SATURATION 0.8
#define EF_DEEP_DARK_STRENGTH 0.65
#define EF_RD_DARK_TONE_LINEAR_SCALE 0.74544862
#define EF_RD_LIGHT_TONE_LINEAR_SCALE 1.56278558
#define EF_RD_SELF_SHADOW_STRENGTH 1.0

#define EF_GOO_RIM_WIDTH_X 0.041847
#define EF_GOO_RIM_WIDTH_Y 0.019108
#define EF_GOO_DEPTH_RIM_VIEW_SCALE 0.1
#define EF_GOO_DEPTH_RIM_MODEL_SCALE 10.0
#define EF_GOO_DEPTH_RIM_DELTA_SCALE 0.8
#define EF_GOO_DEPTH_RIM_MAX 4.0
#define EF_GOO_RIM_FRESNEL_POWER 4.0
#define EF_GOO_RIM_DIRECTIONAL_ATTENUATION 0.961783409
#define EF_GOO_RIM_LIMITATION_STRENGTH 0.35
#define EF_GOO_RIM_COLOR float3(1.0, 1.0, 1.0)
#define EF_GOO_RIM_COLOR_STRENGTH 2.0

#define EF_HAIR_KK_SPHERE_HN_BLEND 0.25
#define EF_HAIR_KK_RANGE 320.0
#define EF_HAIR_HIGHLIGHT_SCALE_X 1.0
#define EF_HAIR_HIGHLIGHT_SCALE_Y 1.0
#define EF_HAIR_ANISO_NOISE_UV_ST float4(1.5, 1.0, 0.0, 0.0)
#define EF_HAIR_ANISO_NOISE_STRENGTH 0.16
#define EF_HAIR_ANISO_BASE_OFFSET 0.55
#define EF_HAIR_ANISO_CUT_OFFSET 0.25
#define EF_HAIR_RS_U_POWER 1.0
#define EF_HAIR_RS_GAIN 7.0
#define EF_HAIR_LINE_UV_ST float4(1.0, 1.0, 0.0, 0.0)

#define EF_HAIR_TOP_LIGHT_COLOR float3(0.92, 0.96, 1.0)
#define EF_HAIR_TOP_LIGHT_STRENGTH 0.12
#define EF_HAIR_TOP_LIGHT_OFFSET 0.0
#define EF_HAIR_TOP_LIGHT_THRESHOLD 0.45
#define EF_HAIR_TOP_LIGHT_SOFTNESS 0.25
#define EF_HAIR_TOP_LIGHT_NORMAL_DETAIL 0.25
#define EF_HAIR_DARK_LINE_STRENGTH 0.70
#define EF_HAIR_DARK_LINE_SATURATION 0.80
#define EF_HAIR_DARK_LINE_SPECULAR_PROTECT 3.0

#define EF_DOMAIN 1
#define EF_CULL_MODE NONE
#define EF_USE_ORM 1
#define EF_USE_NORMAL_MAP 1
#define EF_USE_SPHERE_NORMAL 0
#define EF_USE_OUTLINE 0
#define EF_OUTLINE_CONTROLLER_ENABLED 0
#define EF_HAIR_SPEC_OFF 1
#define EF_DEBUG_SOLID 0

#include "internal/endfield_shader.hlsl"
