using System.Globalization;
using System.Text.RegularExpressions;

namespace EndfieldMaterialStudio.Core;

public static class ZzzProfileIncludeWriter
{
    // DX9/MME rejects the tiny 1x1 PNG used by the first prototype. Keep a
    // conservative 4x4 24-bit BMP so disabled slots still create cleanly.
    public const string NeutralResource = "generated_json_profiles/ZZZ_JSON_NeutralMatCap.bmp";

    public static byte[] NeutralTextureBytes() => Convert.FromBase64String(
        "Qk1mAAAAAAAAADYAAAAoAAAABAAAAAQAAAABABgAAAAAAAAAAADEDgAAxA4AAAAAAAAAAAAA////////////////////////////////////////////////////////////////");

    public static string Build(
        MaterialAssignment material,
        TextureSlots packagedTextures,
        string profileName)
    {
        var profile = material.Zzz;
        var guard = Regex.Replace(profileName.ToUpperInvariant(), "[^A-Z0-9]", "_");
        var lines = new List<string>
        {
            "// Generated by ZZZ Material Studio. Manual MatCap bindings are authoritative.",
            $"// Source: {Path.GetFileName(profile.OfficialJsonPath ?? "manual")}",
            $"#ifndef ZZZ_JSON_PROFILE_{guard}_INCLUDED",
            $"#define ZZZ_JSON_PROFILE_{guard}_INCLUDED",
            string.Empty,
            DefineResource("ZZZ_JSON_DIFFUSE_RESOURCE", packagedTextures.Base),
            DefineResource("ZZZ_JSON_NORMAL_RESOURCE", packagedTextures.Normal),
            DefineResource("ZZZ_JSON_MATERIAL_RESOURCE", packagedTextures.Property),
            DefineResource("ZZZ_JSON_ATTRIBUTE_RESOURCE", packagedTextures.Rs),
            string.Empty
        };

        for (var slot = 1; slot <= 5; slot++)
        {
            var resource = packagedTextures.MatCaps.TryGetValue(slot, out var value) ? value : null;
            lines.Add(DefineResource($"ZZZ_JSON_MATCAP_SLOT_{slot}_RESOURCE", resource, NeutralResource));
        }

        var primarySlot = Enumerable.Range(1, 5)
            .FirstOrDefault(slot =>
            {
                var binding = profile.GetMatCap(slot);
                return binding.Enabled && packagedTextures.MatCaps.TryGetValue(slot, out var resource) &&
                       !string.IsNullOrWhiteSpace(resource);
            });
        lines.Add($"#define ZZZ_JSON_MATCAP_PRIMARY_SLOT {primarySlot}");
        lines.Add(DefineResource(
            "ZZZ_JSON_MATCAP_PRIMARY_RESOURCE",
            primarySlot == 0 ? null : packagedTextures.MatCaps[primarySlot],
            NeutralResource));

        lines.Add(string.Empty);
        lines.Add($"static const float ZZZ_JsonMatcapMasterEnabled = {Hlsl(ProfileFloat(profile, "_MatCap", 1.0) > 0.5 ? 1.0 : 0.0)};");
        lines.Add($"static const float ZZZ_JsonMatcapUseMask = {Hlsl(ProfileFloat(profile, "_UseMatCapMask", 1.0))};");
        lines.Add($"static const float ZZZ_JsonSpecularHighlights = {Hlsl(ProfileFloat(profile, "_SpecularHighlights", 1.0))};");
        lines.Add($"static const float ZZZ_JsonSpecularIntensity = {Hlsl(ProfileFloat(profile, "_SpecIntensity", 0.1))};");
        lines.Add($"static const float ZZZ_JsonMetallic = {Hlsl(ProfileFloat(profile, "_Metallic", 1.0))};");
        lines.Add($"static const float ZZZ_JsonGlossiness = {Hlsl(ProfileFloat(profile, "_Glossiness", 1.0))};");
        lines.Add(string.Empty);

        for (var slot = 1; slot <= 5; slot++)
        {
            var binding = profile.GetMatCap(slot);
            var suffix = slot == 1 ? string.Empty : slot.ToString(CultureInfo.InvariantCulture);
            var colorBurst = ProfileFloat(profile, "_MatCapColorBurst" + suffix, 1.0) * Math.Max(binding.Intensity, 0.0);
            var alphaBurst = ProfileFloat(profile, "_MatCapAlphaBurst" + suffix, 1.0);
            var blendMode = BlendMode(binding.BlendMode, ProfileFloat(profile, "_MatCapBlendMode" + suffix, 0.0));
            var texId = ProfileFloat(profile, "_MatCapTexID" + suffix, 100.0);
            var refract = ProfileFloat(profile, "_MatCapRefract" + suffix, 0.0);
            var uSpeed = ProfileFloat(profile, "_MatCapUSpeed" + suffix, 0.0);
            var vSpeed = ProfileFloat(profile, "_MatCapVSpeed" + suffix, 0.0);
            var specularColor = ProfileColor(profile, "_SpecularColor" + suffix);
            var specularRange = ProfileFloat(profile, "_SpecularRange" + suffix, 1.0);
            var toonSpecular = ProfileFloat(profile, "_ToonSpecular" + suffix, 0.01);
            var modelSize = ProfileFloat(profile, "_ModelSize" + suffix, 1.0);
            var hasPackagedTexture = packagedTextures.MatCaps.TryGetValue(slot, out var resource) && !string.IsNullOrWhiteSpace(resource);
            var enabled = binding.Enabled && hasPackagedTexture;
            lines.Add($"static const float ZZZ_JsonMatcapEnabled{slot} = {Hlsl(enabled ? 1.0 : 0.0)};");
            lines.Add($"static const float3 ZZZ_JsonMatcapTint{slot} = {Hlsl(binding.Tint)};");
            lines.Add($"static const float ZZZ_JsonMatcapColorBurst{slot} = {Hlsl(colorBurst)};");
            lines.Add($"static const float ZZZ_JsonMatcapAlphaBurst{slot} = {Hlsl(alphaBurst)};");
            lines.Add($"static const float ZZZ_JsonMatcapBlendMode{slot} = {Hlsl(blendMode)};");
            lines.Add($"static const float ZZZ_JsonMatcapTexId{slot} = {Hlsl(texId)};");
            lines.Add($"static const float ZZZ_JsonMatcapRefract{slot} = {Hlsl(refract)};");
            lines.Add($"static const float ZZZ_JsonMatcapUSpeed{slot} = {Hlsl(uSpeed)};");
            lines.Add($"static const float ZZZ_JsonMatcapVSpeed{slot} = {Hlsl(vSpeed)};");
            lines.Add($"static const float ZZZ_JsonMatcapMaskChannel{slot} = {Hlsl(MaskChannel(binding.MaskChannel))};");
            lines.Add($"static const float ZZZ_JsonMatcapRotation{slot} = {Hlsl(binding.Rotation)};");
            lines.Add($"static const float2 ZZZ_JsonMatcapScale{slot} = float2({Hlsl(binding.Scale)}, {Hlsl(binding.ScaleY)});");
            lines.Add($"static const float2 ZZZ_JsonMatcapOffset{slot} = float2({Hlsl(binding.OffsetX)}, {Hlsl(binding.OffsetY)});");
            lines.Add($"static const float3 ZZZ_JsonSpecularColor{slot} = {Hlsl(specularColor)};");
            lines.Add($"static const float ZZZ_JsonSpecularRange{slot} = {Hlsl(specularRange)};");
            lines.Add($"static const float ZZZ_JsonToonSpecular{slot} = {Hlsl(toonSpecular)};");
            lines.Add($"static const float ZZZ_JsonModelSize{slot} = {Hlsl(modelSize)};");
            lines.Add(string.Empty);
        }
        lines.Add("#endif");
        lines.Add(string.Empty);
        return string.Join("\r\n", lines);
    }

    private static string DefineResource(string name, string? value, string fallback = "") =>
        $"#define {name} \"{EscapeResource(string.IsNullOrWhiteSpace(value) ? fallback : value)}\"";

    private static string EscapeResource(string value) => value.Replace('\\', '/').Replace("\"", "\\\"");

    private static double ProfileFloat(ZzzMaterialProfile profile, string name, double fallback) =>
        profile.OfficialFloats.TryGetValue(name, out var value) && double.IsFinite(value) ? value : fallback;

    private static ZzzColorValue ProfileColor(ZzzMaterialProfile profile, string name) =>
        profile.OfficialColors.TryGetValue(name, out var value) ? value : new ZzzColorValue();

    private static double BlendMode(string value, double fallback) => value.Trim().ToLowerInvariant() switch
    {
        "alphablend" or "alpha" or "alphablended" => 0.0,
        "add" => 1.0,
        "overlay" => 2.0,
        "replace" => 3.0,
        "multiply" => 4.0,
        "official" or "json" or "" => fallback,
        _ => fallback
    };

    private static double MaskChannel(string value) => value.Trim().ToUpperInvariant() switch
    {
        "R" => 0.0,
        "G" => 1.0,
        "B" => 2.0,
        "A" => 3.0,
        "RGB" => 4.0,
        "RGBA" => 5.0,
        _ => 2.0
    };

    private static string Hlsl(double value)
    {
        var text = value.ToString("0.#########", CultureInfo.InvariantCulture);
        return text.Contains('.') ? text : text + ".0";
    }

    private static string Hlsl(ZzzColorValue color) =>
        $"float3({Hlsl(color.R)}, {Hlsl(color.G)}, {Hlsl(color.B)})";
}
